title:     Shruti Tambe
logo: /assets/img/me.png
description: Hi, I am pursuing a Masters in Information Systems at Northeastern University. As a Software Engineer, I bring expertise in Python, Java and SQL. Currently, I am looking for opportunities in data science.
show_downloads: true
theme: jekyll-theme-minimal
